defaults:
  - /habitat: habitat_config_base
  - /habitat/dataset: dataset_config_schema
  - /habitat/task: vln_r2r
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 50

  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 480
            height: 270
            hfov: 120
            type: HabitatSimRGBSensor
          depth_sensor:
            width: 480
            height: 270
            hfov: 120
            type: HabitatSimDepthSensor
          semantic_sensor:
            width: 480
            height: 270
            hfov: 120
            type: HabitatSimSemanticSensor

    forward_step_size: 0.25
    turn_angle: 15
    
  dataset:
    type: R2RVLN-v1
    split: val_unseen
    data_path: "data/datasets/vln/mp3d/r2r/v1/{split}/{split}.json.gz"
    scenes_dir: "data/scene_datasets/mp3d/"
